cacheFolder: ./.yarn/cache
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.12.0.cjs
packageExtensions:
    # deasync didn't add node-gyp as a direct dependency so it fails to build in
    # Yarn (https://github.com/yarnpkg/berry/issues/5804), so extend its pkg.json config here.
    deasync@*:
        dependencies:
            node-gyp: 'latest'
