const darkest = require('../darkest.js');
const dimensionGlobals = require('../dimensionGlobals.js');
const large = require('../large.js');
exports["folder-background-color"] = darkest["gray-300"];
exports["file-background-color"] = darkest["gray-50"];
exports["icon-outline-color"] = darkest["gray-500"];
exports["icon-max-width"] = dimensionGlobals["size-1000"];
exports["icon-min-width"] = large["size-600"];
exports["icon-margin"] = large["size-250"];
