const darkest = require('../darkest.js');
const staticAliases = require('../staticAliases.js');
const dimensionGlobals = require('../dimensionGlobals.js');
exports["border-color"] = darkest["blue-400"];
exports["circle-border-color"] = darkest["blue-400"];
exports["circle-border-fill"] = darkest["background-color-transparent"];
exports["border-size"] = staticAliases["border-size-thick"];
exports["circle-border-size"] = staticAliases["border-size-thick"];
exports["circle-size"] = dimensionGlobals["size-150"];
