import { Variants } from "@spectrum-css/preview/decorators";
import { Template } from "./template.js";

export const CheckboxGroup = Variants({
	Template,
	stateDirection: "row",
	sizeDirection: "row",
	testData: [
		{
			testHeading: "Default",
		},
		{
			testHeading: "Emphasized",
			isEmphasized: true,
		},
		{
			testHeading: "Truncation",
			withStates: false,
			label: "Checkbox with an extraordinarily long label. Please don't do this but if you did, it should wrap text when it gets longer than the container that houses the checkbox with the unacceptably long label",
			customStyles: {
				"max-width": "200px",
			}
		}
	],
	stateData: [
		{
			testHeading: "Default",
		},
		{
			testHeading: "Checked",
			isChecked: true,
		},
		{
			testHeading: "Hovered",
			isHovered: true,
		},
		{
			testHeading: "Focused",
			isFocused: true,
		},
		{
			testHeading: "Active",
			isActive: true,
		},
		{
			testHeading: "Indeterminate",
			isIndeterminate: true,
		},
		{
			testHeading: "Checked + Hovered",
			isChecked: true,
			isHovered: true,
		},
		{
			testHeading: "Checked + Focused",
			isChecked: true,
			isFocused: true,
		},
		{
			testHeading: "Checked + Indeterminate",
			isChecked: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Hovered + Focused",
			isHovered: true,
			isFocused: true,
		},
		{
			testHeading: "Hovered + Indeterminate",
			isHovered: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Focused + Indeterminate",
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Checked + Hovered + Focused",
			isChecked: true,
			isHovered: true,
			isFocused: true,
		},
		{
			testHeading: "Checked + Hovered + Indeterminate",
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Checked + Focused + Indeterminate",
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Checked + Hovered + Focused + Indeterminate",
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Hovered + Focused + Indeterminate",
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid",
			isInvalid: true,
		},
		{
			testHeading: "Invalid + Checked",
			isInvalid: true,
			isChecked: true,
		},
		{
			testHeading: "Invalid + Hovered",
			isInvalid: true,
			isHovered: true,
		},
		{
			testHeading: "Invalid + Focused",
			isInvalid: true,
			isFocused: true,
		},
		{
			testHeading: "Invalid + Indeterminate",
			isInvalid: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
		},
		{
			testHeading: "Invalid + Checked + Focused",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
		},
		{
			testHeading: "Invalid + Checked + Indeterminate",
			isInvalid: true,
			isChecked: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Hovered + Focused",
			isInvalid: true,
			isHovered: true,
			isFocused: true,
		},
		{
			testHeading: "Invalid + Hovered + Indeterminate",
			isInvalid: true,
			isHovered: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Focused + Indeterminate",
			isInvalid: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Indeterminate",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Indeterminate",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Hovered + Focused + Indeterminate",
			isInvalid: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Indeterminate",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
		},
		{
			testHeading: "Disabled",
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Disabled",
			isInvalid: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Disabled",
			isChecked: true,
			isDisabled: true,
		},
		{
			testHeading: "Hovered + Disabled",
			isHovered: true,
			isDisabled: true,
		},
		{
			testHeading: "Focused + Disabled",
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Indeterminate + Disabled",
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Disabled",
			isInvalid: true,
			isChecked: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Hovered + Disabled",
			isInvalid: true,
			isHovered: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Focused + Disabled",
			isInvalid: true,
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Indeterminate + Disabled",
			isInvalid: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Hovered + Disabled",
			isChecked: true,
			isHovered: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Focused + Disabled",
			isChecked: true,
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Indeterminate + Disabled",
			isChecked: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Hovered + Focused + Disabled",
			isHovered: true,
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Hovered + Indeterminate + Disabled",
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Focused + Indeterminate + Disabled",
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Disabled",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Disabled",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Hovered + Indeterminate + Disabled",
			isInvalid: true,
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Focused + Indeterminate + Disabled",
			isInvalid: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Hovered + Indeterminate + Disabled",
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Focused + Indeterminate + Disabled",
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Hovered + Focused + Indeterminate + Disabled",
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Disabled",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Indeterminate + Disabled",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Indeterminate + Disabled",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Hovered + Focused + Indeterminate + Disabled",
			isInvalid: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Checked + Hovered + Focused + Indeterminate + Disabled",
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Indeterminate + Disabled",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
		},
		{
			testHeading: "Read-only",
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Read-only",
			isChecked: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Read-only",
			isHovered: true,
			isReadOnly: true,
		},
		{
			testHeading: "Focused + Read-only",
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Indeterminate + Read-only",
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Read-only",
			isInvalid: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Read-only",
			isInvalid: true,
			isChecked: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Hovered + Read-only",
			isInvalid: true,
			isHovered: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Focused + Read-only",
			isInvalid: true,
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Indeterminate + Read-only",
			isInvalid: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Hovered + Read-only",
			isChecked: true,
			isHovered: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Focused + Read-only",
			isChecked: true,
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Indeterminate + Read-only",
			isChecked: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Focused + Read-only",
			isHovered: true,
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Indeterminate + Read-only",
			isHovered: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Focused + Indeterminate + Read-only",
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Read-only",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Hovered + Indeterminate + Read-only",
			isInvalid: true,
			isHovered: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Focused + Indeterminate + Read-only",
			isInvalid: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Hovered + Indeterminate + Read-only",
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Focused + Indeterminate + Read-only",
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Focused + Indeterminate + Read-only",
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Indeterminate + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Indeterminate + Read-only",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Hovered + Focused + Indeterminate + Read-only",
			isInvalid: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Hovered + Focused + Indeterminate + Read-only",
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Indeterminate + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isReadOnly: true,
		},
		{
			testHeading: "Disabled + Read-only",
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Disabled + Read-only",
			isInvalid: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Disabled + Read-only",
			isChecked: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Disabled + Read-only",
			isHovered: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Focused + Disabled + Read-only",
			isFocused: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Indeterminate + Disabled + Read-only",
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Disabled + Read-only",
			isInvalid: true,
			isChecked: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Hovered + Disabled + Read-only",
			isInvalid: true,
			isHovered: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Focused + Disabled + Read-only",
			isInvalid: true,
			isFocused: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Indeterminate + Disabled + Read-only",
			isInvalid: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Hovered + Disabled + Read-only",
			isChecked: true,
			isHovered: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Focused + Disabled + Read-only",
			isChecked: true,
			isFocused: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Indeterminate + Disabled + Read-only",
			isChecked: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Hovered + Indeterminate + Disabled + Read-only",
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Focused + Indeterminate + Disabled + Read-only",
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Disabled + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Focused + Disabled + Read-only",
			isInvalid: true,
			isChecked: true,
			isFocused: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Hovered + Indeterminate + Disabled + Read-only",
			isInvalid: true,
			isHovered: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Focused + Indeterminate + Disabled + Read-only",
			isInvalid: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Checked + Hovered + Focused + Indeterminate + Disabled + Read-only",
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
		{
			testHeading: "Invalid + Checked + Hovered + Focused + Indeterminate + Disabled + Read-only",
			isInvalid: true,
			isChecked: true,
			isHovered: true,
			isFocused: true,
			isIndeterminate: true,
			isDisabled: true,
			isReadOnly: true,
		},
	],
});
