name: Auto_Push

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: adobe/spectrum-css-vr-results@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
