name: Azure Static Web Apps CI/CD

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Delete old deploy comments
        run: |
          $pr = "${{ github.event.pull_request.number }}"
          gh api repos/${{ github.repository }}/issues/$pr/comments `
            | ConvertFrom-Json `
            | Where-Object body -like 'Azure Static Web Apps: Your stage site is ready! Visit it here: *' `
            | ForEach-Object {
                gh api repos/${{ github.repository }}/issues/comments/$($_.id) -X DELETE
              }
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy to Azure static web apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_CLIFF_0173AA90F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          app_build_command: "yarn build:docs"

  close_pull_request_job:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Clean up PR environment
    steps:
      - name: Remove PR environment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_CLIFF_0173AA90F }}
          action: "close"
