name: Linting

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - "**.css"

jobs:
  styles:
    name: Lint CSS

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node LTS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Compile assets
        run: yarn build
      - name: Lint assets using stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
