name: Publish documentation
#
# This workflow publishes the documentation to Fastly
#

on:
    workflow_dispatch:
        inputs:
            deploy-message:
                required: false
                type: string
            alias:
                required: false
                type: string
    workflow_call:
        inputs:
            deploy-message:
                required: false
                type: string
            alias:
                required: false
                type: string

permissions:
    contents: read
    pull-requests: write

jobs:
    publish_site:
        name: Publish to Fastly
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            ## --- SETUP --- ##
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node LTS version
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Enable Corepack
              run: corepack enable

            ## --- YARN CACHE --- ##
            - name: Check for cached dependencies
              continue-on-error: true
              id: cache-dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      .cache/yarn
                      node_modules
                  key: ubuntu-latest-node20-${{ hashFiles('yarn.lock') }}

            ## --- INSTALL --- ##
            # note: if cache-hit isn't needed b/c yarn will leverage the cache if it exists
            - name: Install dependencies
              shell: bash
              run: yarn install --immutable

            ## --- BUILD --- ##
            - name: Build storybook
              shell: bash
              run: yarn build:docs

            - name: Set up Fastly CLI
              uses: fastly/compute-actions/setup@v11
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Copy fastly.toml to dist
              run: cp fastly.toml dist/fastly.toml

            - name: Install Fastly CLI
              run: npm install -g @fastly/cli@latest

            - name: Create service with PR number
              id: service-name
              working-directory: ${{ inputs.project_directory }}
              run: echo "SERVICE_NAME=$(yq '.name' fastly.toml)-${{ github.event.number }}" >> "$GITHUB_OUTPUT"
              shell: bash

            - name: Fastly static publish
              env:
                FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
              run: npx @fastly/compute-js-static-publish@latest --root-dir=./dist --kv-store-name=spectrum-css-test --publish-content=spectrum-css && cd ./compute-js && npx @fastly/compute-js-static-publish publish-content --collection-name=${{ steps.service-name.outputs.SERVICE_NAME }}
